#!/bin/bash

DOT="$(dirname $(realpath $0))"

function reln {
	rm -f ~/$2
	ln -rs $DOT/$1 ~/$2
}

reln bash/rc .bashrc
reln bash/profile .bash_profile
reln tmux .tmux.conf
reln nano .nanorc
reln git .gitconfig
